In [202]:
# Import the numpy package under the name np
import numpy as np

In [201]:
# Create a null vector of size 10
a =np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#Create a vector with values ranging from 10 to 49
b=np.arange(10,49)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [45]:
#Find the shape of previous array in question 3
np.shape(b)

(39,)

In [46]:
#Print the type of the previous array in question 3
b.dtype

dtype('int32')

In [57]:
#Print the numpy version and the configuration
print(np. __version__)

1.19.2


In [55]:
pip list

Package                            VersionNote: you may need to restart the kernel to use updated packages.
---------------------------------- -------------------
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.10.0

anaconda-project                   0.8.3
argh                               0.26.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.4.2
astropy                            4.0.2
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              20.3.0
autopep8                           1.5.4
Babel                              2.8.1
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
bcrypt                             3.2.0
beautifuls

In [58]:
#Print the dimension of the array in question 3
np.ndim(b)

1

In [60]:
#Create a boolean array with all the True values
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [66]:
ab=b>9
ab

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [67]:
#Create a two dimensional array
tdim=np.array([[1,2,3,],[4,5,6]])
tdim

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
s=np.random.rand(10,2)
s

array([[0.45935306, 0.02870486],
       [0.19384715, 0.56900001],
       [0.89614126, 0.83398809],
       [0.2707629 , 0.14423508],
       [0.87467695, 0.60537027],
       [0.74677818, 0.71812855],
       [0.37074539, 0.19367413],
       [0.26009242, 0.12364641],
       [0.34472296, 0.2522795 ],
       [0.91877578, 0.36706256]])

In [69]:
#Create a three dimensional array
t=np.zeros((3,4,5))
t


array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [72]:
#Difficulty Level Easy

#Reverse a vector (first element becomes last)
p=np.array([1,2,3,4,5,6,7])
flipped = np.flip(p)
flipped

array([7, 6, 5, 4, 3, 2, 1])

In [91]:
#Create a null vector of size 10 but the fifth value which is 1
import numpy as np
null =np.zeros(10)
null[4]=1
null

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [88]:
#Create a 3x3 identity matrix
t3=np.zeros((3,3))
t3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [92]:
#arr = np.array([1, 2, 3, 4, 5])
#Convert the data type of the given array from int to float
arr = np.array([1, 2, 3, 4, 5])
arr=arr.astype('float64')
arr.dtype

dtype('float64')

In [93]:
#arr1 = np.array([[1., 2., 3.],

           # [4., 5., 6.]])  

#arr2 = np.array([[0., 4., 1.],

         #  [7., 2., 12.]])
#Multiply arr1 with arr2
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [7]:
#
#arr1 = np.array([[1., 2., 3.],

            #[4., 5., 6.]]) 

#arr2 = np.array([[0., 4., 1.],

        # [7., 2., 12.]])
#Make an array by comparing both the arrays provided above
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
compare=arr1==arr2
compare

array([[False, False, False],
       [False, False, False]])

In [71]:
# Extract all odd numbers from arr with values(0-9)
import numpy as np
q=np.array([1,2,3,4,5,6,7,8,9])
q1=np.where(q%2==0)
q1

(array([1, 3, 5, 7], dtype=int64),)

In [75]:
### Replace all odd numbers to -1 from previous array
q=np.array([1,2,3,4,5,6,7,8,9])
q1=np.where(q%2,-1,q)
q1


array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

In [78]:
#arr = np.arange(10)
#Replace the values of indexes 5,6,7 and 8 to 12
arr = np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [88]:
#Create a 2d array with 1 on the border and 0 inside
c=np.ones((5,5))
c[1:-1,1:-1]=0
c

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [90]:
#Difficulty Level Medium

#arr2d = np.array([[1, 2, 3],

            #[4, 5, 6], 

            #[7, 8, 9]])
        #Replace the value 5 to 12
arr2d=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])   
arr2d[1:-1,1:-1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [97]:
#arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
#Convert all the values of 1st array to 64
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [112]:
#Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it
arr2=np.array([[0,1,2,3,4], [5,6,7,8,9]])
sliced=arr2[0]  
sliced

array([0, 1, 2, 3, 4])

In [113]:
#Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it
arr2=np.array([[0,1,2,3,4], [5,6,7,8,9]])
sliced=arr2[1][1]
sliced

6

In [120]:
#Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows
arr2=np.array([[0,1,2,3,4], [5,6,7,8,9]])
arr4=arr2[0:2,2:3]
arr4

array([[2],
       [7]])

In [124]:
#Create a 10x10 array with random values and find the minimum and maximum values
arr5=np.random.rand(10,10)
np.max(arr5)

0.9991417332049025

In [125]:
np.min(arr5)

0.0028000923748366935

In [127]:
#27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
#Find the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)


array([2, 4])

In [128]:
#a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
#Find the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b,'okay','not okay')

array(['not okay', 'okay', 'not okay', 'okay', 'not okay', 'okay',
       'not okay', 'okay', 'not okay', 'not okay'], dtype='<U8')

In [131]:
#names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
#Find all the values from array data where the values from array names are not equal to Will
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names!='will']

array([[-1.0270327 , -1.03925798, -1.04487067,  1.93643992],
       [ 0.24514647, -0.72330947,  0.7007763 ,  1.10967256],
       [ 0.55648477, -0.86707579,  0.49531066, -1.2386996 ],
       [ 0.7121121 , -0.82381122,  0.50517624, -0.67093458],
       [ 0.51078555, -0.74164069, -1.00288757,  0.02250108],
       [ 0.02988512, -0.69015739, -1.94822574,  0.37730388],
       [-0.88578364,  1.98391111,  0.11550137, -0.8524082 ]])

In [135]:
#names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
#Find all the values from array data where the values from array names are not equal to Will and Joe
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
d2=(names!='will')|(names!='joe')
d2

array([ True,  True,  True,  True,  True,  True,  True])

In [144]:
#Difficulty Level Hard

#Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.
as1=np.arange(1,16)
as2=as1.reshape(5,3)
as2.astype('float64')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

In [146]:
#Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.
as1=np.arange(1,17)
as2=as1.reshape(2,2,4)
as2.astype('float64')

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

In [154]:
#Swap axes of the array you created in Question 32
as1=np.arange(1,17)
as2=as1.reshape(2,2,4)
w2=np.vstack(as1)
w2.astype('float64')

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.],
       [11.],
       [12.],
       [13.],
       [14.],
       [15.],
       [16.]])

In [155]:
w2=np.hstack(as1)
w2.astype('float64')

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16.])

In [163]:
#Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0
arr=np.arange(0.1,10)
sqr=np.sqrt(s1)
output=np.where(sqr<0.5,0,sqr)
output

array([0.        , 1.04880885, 1.44913767, 1.76068169, 2.02484567,
       2.25831796, 2.46981781, 2.66458252, 2.84604989, 3.01662063])

In [170]:
#Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays
ar=np.random.randn(1,12)
ar1=np.random.randn(1,12)
maxvalues=np.maximum(ar,ar1)
maxvalues


array([[ 0.3534353 , -0.60694791,  1.4867326 , -0.66662616,  1.01402844,
        -0.36091256,  1.03245543,  2.10752962,  0.90061075,  0.78544331,
         0.87589479, -0.75904236]])

In [174]:
#names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
#Find the unique names and sort them out!
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
st=np.unique(names)
st

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [175]:
st=np.sort(names)
st

array(['Bob', 'Bob', 'Joe', 'Joe', 'Joe', 'Will', 'Will'], dtype='<U4')

In [177]:
#a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])
#From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
re1=np.delete(a,4)
re1

array([1, 2, 3, 4])

In [190]:
#Following is the input NumPy array delete column two and insert following new column in its place.
#sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

#newColumn = numpy.array([[10,10,10]])

sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray[2:3]=10
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [10, 10, 10]])

In [194]:
#x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])
#Find the dot product of the above two matrix
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
w=x.dot(y)
w

array([[ 28.,  64.],
       [ 67., 181.]])

In [200]:
#Generate a matrix of 20 random values and find its cumulative sum
values=np.arange(0,20)
values
values.cumsum()

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190], dtype=int32)